use crate::Context;

use sokol_app_sys::sokol_app::{self, sapp_keycode};

#[derive(Debug, Copy, Clone, PartialEq, Hash, Eq)]
pub enum MouseButton {
    Right,
    Left,
}
#[derive(Debug, Copy, Clone, PartialEq, Hash, Eq)]
pub enum KeyCode {
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
    Unknown(u32),
}

impl From<sapp_keycode> for KeyCode {
    fn from(key_code: sapp_keycode) -> KeyCode {
        match key_code {
            sokol_app::sapp_keycode_SAPP_KEYCODE_SPACE => KeyCode::Space,
            sokol_app::sapp_keycode_SAPP_KEYCODE_APOSTROPHE => KeyCode::Apostrophe,
            sokol_app::sapp_keycode_SAPP_KEYCODE_COMMA => KeyCode::Comma,
            sokol_app::sapp_keycode_SAPP_KEYCODE_MINUS => KeyCode::Minus,
            sokol_app::sapp_keycode_SAPP_KEYCODE_PERIOD => KeyCode::Period,
            sokol_app::sapp_keycode_SAPP_KEYCODE_SLASH => KeyCode::Slash,
            sokol_app::sapp_keycode_SAPP_KEYCODE_0 => KeyCode::Key0,
            sokol_app::sapp_keycode_SAPP_KEYCODE_1 => KeyCode::Key1,
            sokol_app::sapp_keycode_SAPP_KEYCODE_2 => KeyCode::Key2,
            sokol_app::sapp_keycode_SAPP_KEYCODE_3 => KeyCode::Key3,
            sokol_app::sapp_keycode_SAPP_KEYCODE_4 => KeyCode::Key4,
            sokol_app::sapp_keycode_SAPP_KEYCODE_5 => KeyCode::Key5,
            sokol_app::sapp_keycode_SAPP_KEYCODE_6 => KeyCode::Key6,
            sokol_app::sapp_keycode_SAPP_KEYCODE_7 => KeyCode::Key7,
            sokol_app::sapp_keycode_SAPP_KEYCODE_8 => KeyCode::Key8,
            sokol_app::sapp_keycode_SAPP_KEYCODE_9 => KeyCode::Key9,
            sokol_app::sapp_keycode_SAPP_KEYCODE_SEMICOLON => KeyCode::Semicolon,
            sokol_app::sapp_keycode_SAPP_KEYCODE_EQUAL => KeyCode::Equal,
            sokol_app::sapp_keycode_SAPP_KEYCODE_A => KeyCode::A,
            sokol_app::sapp_keycode_SAPP_KEYCODE_B => KeyCode::B,
            sokol_app::sapp_keycode_SAPP_KEYCODE_C => KeyCode::C,
            sokol_app::sapp_keycode_SAPP_KEYCODE_D => KeyCode::D,
            sokol_app::sapp_keycode_SAPP_KEYCODE_E => KeyCode::E,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F => KeyCode::F,
            sokol_app::sapp_keycode_SAPP_KEYCODE_G => KeyCode::G,
            sokol_app::sapp_keycode_SAPP_KEYCODE_H => KeyCode::H,
            sokol_app::sapp_keycode_SAPP_KEYCODE_I => KeyCode::I,
            sokol_app::sapp_keycode_SAPP_KEYCODE_J => KeyCode::J,
            sokol_app::sapp_keycode_SAPP_KEYCODE_K => KeyCode::K,
            sokol_app::sapp_keycode_SAPP_KEYCODE_L => KeyCode::L,
            sokol_app::sapp_keycode_SAPP_KEYCODE_M => KeyCode::M,
            sokol_app::sapp_keycode_SAPP_KEYCODE_N => KeyCode::N,
            sokol_app::sapp_keycode_SAPP_KEYCODE_O => KeyCode::O,
            sokol_app::sapp_keycode_SAPP_KEYCODE_P => KeyCode::P,
            sokol_app::sapp_keycode_SAPP_KEYCODE_Q => KeyCode::Q,
            sokol_app::sapp_keycode_SAPP_KEYCODE_R => KeyCode::R,
            sokol_app::sapp_keycode_SAPP_KEYCODE_S => KeyCode::S,
            sokol_app::sapp_keycode_SAPP_KEYCODE_T => KeyCode::T,
            sokol_app::sapp_keycode_SAPP_KEYCODE_U => KeyCode::U,
            sokol_app::sapp_keycode_SAPP_KEYCODE_V => KeyCode::V,
            sokol_app::sapp_keycode_SAPP_KEYCODE_W => KeyCode::W,
            sokol_app::sapp_keycode_SAPP_KEYCODE_X => KeyCode::X,
            sokol_app::sapp_keycode_SAPP_KEYCODE_Y => KeyCode::Y,
            sokol_app::sapp_keycode_SAPP_KEYCODE_Z => KeyCode::Z,
            sokol_app::sapp_keycode_SAPP_KEYCODE_LEFT_BRACKET => KeyCode::LeftBracket,
            sokol_app::sapp_keycode_SAPP_KEYCODE_BACKSLASH => KeyCode::Backslash,
            sokol_app::sapp_keycode_SAPP_KEYCODE_RIGHT_BRACKET => KeyCode::RightBracket,
            sokol_app::sapp_keycode_SAPP_KEYCODE_GRAVE_ACCENT => KeyCode::GraveAccent,
            sokol_app::sapp_keycode_SAPP_KEYCODE_WORLD_1 => KeyCode::World1,
            sokol_app::sapp_keycode_SAPP_KEYCODE_WORLD_2 => KeyCode::World2,
            sokol_app::sapp_keycode_SAPP_KEYCODE_ESCAPE => KeyCode::Escape,
            sokol_app::sapp_keycode_SAPP_KEYCODE_ENTER => KeyCode::Enter,
            sokol_app::sapp_keycode_SAPP_KEYCODE_TAB => KeyCode::Tab,
            sokol_app::sapp_keycode_SAPP_KEYCODE_BACKSPACE => KeyCode::Backspace,
            sokol_app::sapp_keycode_SAPP_KEYCODE_INSERT => KeyCode::Insert,
            sokol_app::sapp_keycode_SAPP_KEYCODE_DELETE => KeyCode::Delete,
            sokol_app::sapp_keycode_SAPP_KEYCODE_RIGHT => KeyCode::Right,
            sokol_app::sapp_keycode_SAPP_KEYCODE_LEFT => KeyCode::Left,
            sokol_app::sapp_keycode_SAPP_KEYCODE_DOWN => KeyCode::Down,
            sokol_app::sapp_keycode_SAPP_KEYCODE_UP => KeyCode::Up,
            sokol_app::sapp_keycode_SAPP_KEYCODE_PAGE_UP => KeyCode::PageUp,
            sokol_app::sapp_keycode_SAPP_KEYCODE_PAGE_DOWN => KeyCode::PageDown,
            sokol_app::sapp_keycode_SAPP_KEYCODE_HOME => KeyCode::Home,
            sokol_app::sapp_keycode_SAPP_KEYCODE_END => KeyCode::End,
            sokol_app::sapp_keycode_SAPP_KEYCODE_CAPS_LOCK => KeyCode::CapsLock,
            sokol_app::sapp_keycode_SAPP_KEYCODE_SCROLL_LOCK => KeyCode::ScrollLock,
            sokol_app::sapp_keycode_SAPP_KEYCODE_NUM_LOCK => KeyCode::NumLock,
            sokol_app::sapp_keycode_SAPP_KEYCODE_PRINT_SCREEN => KeyCode::PrintScreen,
            sokol_app::sapp_keycode_SAPP_KEYCODE_PAUSE => KeyCode::Pause,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F1 => KeyCode::F1,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F2 => KeyCode::F2,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F3 => KeyCode::F3,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F4 => KeyCode::F4,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F5 => KeyCode::F5,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F6 => KeyCode::F6,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F7 => KeyCode::F7,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F8 => KeyCode::F8,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F9 => KeyCode::F9,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F10 => KeyCode::F10,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F11 => KeyCode::F11,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F12 => KeyCode::F12,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F13 => KeyCode::F13,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F14 => KeyCode::F14,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F15 => KeyCode::F15,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F16 => KeyCode::F16,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F17 => KeyCode::F17,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F18 => KeyCode::F18,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F19 => KeyCode::F19,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F20 => KeyCode::F20,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F21 => KeyCode::F21,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F22 => KeyCode::F22,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F23 => KeyCode::F23,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F24 => KeyCode::F24,
            sokol_app::sapp_keycode_SAPP_KEYCODE_F25 => KeyCode::F25,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_0 => KeyCode::Kp0,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_1 => KeyCode::Kp1,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_2 => KeyCode::Kp2,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_3 => KeyCode::Kp3,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_4 => KeyCode::Kp4,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_5 => KeyCode::Kp5,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_6 => KeyCode::Kp6,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_7 => KeyCode::Kp7,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_8 => KeyCode::Kp8,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_9 => KeyCode::Kp9,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_DECIMAL => KeyCode::KpDecimal,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_DIVIDE => KeyCode::KpDivide,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_MULTIPLY => KeyCode::KpMultiply,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_SUBTRACT => KeyCode::KpSubtract,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_ADD => KeyCode::KpAdd,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_ENTER => KeyCode::KpEnter,
            sokol_app::sapp_keycode_SAPP_KEYCODE_KP_EQUAL => KeyCode::KpEqual,
            sokol_app::sapp_keycode_SAPP_KEYCODE_LEFT_SHIFT => KeyCode::LeftShift,
            sokol_app::sapp_keycode_SAPP_KEYCODE_LEFT_CONTROL => KeyCode::LeftControl,
            sokol_app::sapp_keycode_SAPP_KEYCODE_LEFT_ALT => KeyCode::LeftAlt,
            sokol_app::sapp_keycode_SAPP_KEYCODE_LEFT_SUPER => KeyCode::LeftSuper,
            sokol_app::sapp_keycode_SAPP_KEYCODE_RIGHT_SHIFT => KeyCode::RightShift,
            sokol_app::sapp_keycode_SAPP_KEYCODE_RIGHT_CONTROL => KeyCode::RightControl,
            sokol_app::sapp_keycode_SAPP_KEYCODE_RIGHT_ALT => KeyCode::RightAlt,
            sokol_app::sapp_keycode_SAPP_KEYCODE_RIGHT_SUPER => KeyCode::RightSuper,
            sokol_app::sapp_keycode_SAPP_KEYCODE_MENU => KeyCode::Menu,
            unknown => KeyCode::Unknown(unknown),
        }
    }
}

#[derive(Debug, Copy, Clone, PartialEq)]
pub enum KeyMods {
    No,
}

pub trait EventHandler {
    fn update(&mut self, _ctx: &mut Context);
    fn draw(&mut self, _ctx: &mut Context);
    fn resize_event(&mut self, _ctx: &mut Context, _width: f32, _height: f32) {}
    fn mouse_motion_event(&mut self, _ctx: &mut Context, _x: f32, _y: f32, _dx: f32, _dy: f32) {}
    fn mouse_wheel_event(&mut self, _ctx: &mut Context, _x: f32, _y: f32) {}
    fn mouse_button_down_event(
        &mut self,
        _ctx: &mut Context,
        _button: MouseButton,
        _x: f32,
        _y: f32,
    ) {
    }
    fn mouse_button_up_event(
        &mut self,
        _ctx: &mut Context,
        _button: MouseButton,
        _x: f32,
        _y: f32,
    ) {
    }

    fn key_down_event(
        &mut self,
        _ctx: &mut Context,
        _keycode: KeyCode,
        _keymods: KeyMods,
        _repeat: bool,
    ) {
    }

    fn key_up_event(&mut self, _ctx: &mut Context, _keycode: KeyCode, _keymods: KeyMods) {}
}
